name: Build and Scan Tetris

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.Krilasi@2004 }}" | docker login -u "${{ secrets.sinchanadev }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t sinchanadev/onenotenotebooks:v1 .

      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'sinchanadev/onenotenotebooks:v1'
          format: 'table'
          exit-code: '1' # This stops the build if it finds scary viruses/vulnerabilities
          severity: 'CRITICAL,HIGH'

      - name: Push to Docker Hub
        run: docker push sinchanadev/onenotenotebooks:v1
